### ISSUE TITLE
IMDb: imdb command not retrieving movie information.

### ISSUE THREAD

**Issue by maduce** [ddan39/Supybot-IMDb#2]
#### User Input In Channel

\<nick> +imdb movie-title 
\<bot> An error has occurred and has been logged. Check the logs for more informations.

#### Output in terminal and logs/message.log:
ERROR 2016-01-05T11:30:54 Uncaught exception in ['imdb'].
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/supybot/callbacks.py", line 1265, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/supybot/utils/python.py", line 86, in g
    f(self, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/supybot/callbacks.py", line 1246, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/supybot/commands.py", line 1053, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/ircbot/supybot/supybot-ProgVal/IMDb/plugin.py", line 109, in imdb
    name = unid(elem[0].text.strip())
IndexError: list index out of range
ERROR 2016-01-05T11:30:54 Exception id: 0x2c5a5

**Comment by ddan39** [comment]
That is from ProgVal's plugins repo, not this repo. I have fixed those errors and recoded/improved the plugin. Remove that one and download from here.
